# 7.2.0 文件存储

之前写出来的应用有一部分也涉及了数据的操作，但是这些数据都存储在内存之中，属于瞬时数据。可能应用关闭或者被意外回收了内存都可能会丢失数据。和瞬时性数据相对的，就是数据持久化。

数据持久化，指的就是将内存中的数据保存到存储设备中，从而保证这些数据即使设备重启也不会丢失。Android提供了3种方式用于简单地实现数据持久化功能：文件存储，SharedPreference存储和数据库存储。

文件存储是一种较为简单的方式，它不对存储的内容进行任何格式化处理，所有的数据都是原封不动地保存进文件的。因此这种方式适合存储一些二进制数据或者文本数据。如果要存储更为复杂的数据，就需要自己定义一套自己的格式规范，方便之后将数据从文件中解析出来。

##### 1 将数据存储到文件中

Context类中自带一个openFileOutput()方法，可以用于将数据存储到指定的文件中。它接收两个参数，第一个是文件名，在创建文件时使用。注意这里的文件名仅仅是文件名而已，不带路径的，因为所有的文件都会默认存进data/data/package name/files下。第二个参数是文件的操作模式，主要有MODE_PRIVATE和MODE_APPEND两种，默认是第一种，效果是如果存在同名文件，就覆盖掉原文件，重新写入数据；第二种不会覆盖原文件，会在原文件的基础上添加数据，如果不存在这个“原文件”就创建新文件。

（其实原本有个MODE_WORLD_READABLE和MODE_WORLD_WRITEABLE，表示允许其他应用对本应用的文件进行读/写操作，但是这两种模式容易引起安全漏洞，在Android 4.2版本被废弃）

openFileOutput()方法返回一个FileOutputStream对象，得到这个对象就可以使用Java流的方式将数据写进文件中了下例展示了如何将一段文本保存到文件中：

```kotlin
fun save(inputText: String) {
    try {
        val output = openFileOutput("data", Context.MODE_PRIVATE)
        val writer = BufferedWriter(OutputStreamWriter(output))
        writer.use{
            it.write(inputText)
        }
    }
    catch(e IOexception) {
        e.printStackTrace()
    }
```

关于流，Java中流的定义如下：

> **Java中对文件的操作是以流的方式进行的。流是Java内存中的一组有序数据序列。Java将数据从源（文件、内存、键盘、网络）读入到内存中，形成了流，然后将这些流还可以写到另外的目的地（文件、内存、控制台、网络），之所以称为流，是因为这个数据序列在不同时刻所操作的是源的不同部分。**

上述代码部分用的是Java流的方式写的，首先，通过openFileOutput()得到一个FileOutputStream对象，用这个对象构建一个OutputStreamWriter对象，接着再使用OutputStreamWriter构建出一个BufferWriter对象。借助这个BufferWriter对象，就可以将文本内容写入文件了。

关于use()，这是Kotlin内置的一个扩展函数。它能在执行完Lambda表达式中的代码之后，自动关闭外层的流。这样就不需要再写一个finally语句手动关闭流了。

另外，kotlin中是没有异常检查机制的，也就是说上述代码的try-catch代码块是依照Java的编程规范写的。在kotlin中，即使不写try-catch也能通过编译。

要理解为什么kotlin取消异常检查机制（Catch Exception机制，简称CE），首先得先理解啥是CE。在程序运行过程中，总会出现各种各样的情况使得某个方法运行不成功。这些“情况”，就可以理解为异常。比如说Thread.sleep()方法，如果当前线程在睡眠的时候，其他线程对这个线程进行中断（thread.interrupt()），那么Thread.sleep()就会中断睡眠，并且抛出一个InterruptedException。当然实际情况会更复杂，可能网不好使得某个请求网络资源的方法没能完成请求，或者本地存储空间不够什么的，这个方法就会根据不同的情况抛出不同的异常。

为了处理这些异常，就有了CE机制。Java规定，对可能抛出的异常，必须被捕获或者抛出，否则程序无法通过编译。这就是try-catch所承担的职责。try里写程序的逻辑，catch里写如果程序发生异常如何处理。如果程序运行完了没有异常，那么就会跳过catch代码块中的代码；如果有异常，那么
